language: ruby

addons:
  postgresql: "11.5"

rvm:
- 2.6.3

before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres

script:

- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec


