language: ruby

rvm:
- 2.3.2

bundler_args: --jobs 1 --retry 3

services:
  - postgresql

  - psql -c 'create database travis_ci_test;' -U postgres

  - cp config/database.yml.travis config/database.yml

script:

 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

cache: bundler

